### ISSUE TITLE
ValueError: I/O operation on closed file

### ISSUE THREAD

**Issue by robnanola** [tumb1er/coverage2clover#21]
after the 2.0.0 update we are getting this error:

> Traceback (most recent call last):
  File "/opt/project/venv/bin/coverage2clover", line 10, in <module>
    sys.exit(main())
  File "/opt/project/venv/lib/python3.6/site-packages/clover/coverage2clover.py", line 23, in main
    cov.open(inputfile)
  File "/opt/project/venv/lib/python3.6/site-packages/clover/__init__.py", line 137, in open
    c.count_loc(sources)
  File "/opt/project/venv/lib/python3.6/site-packages/clover/__init__.py", line 70, in count_loc
    fallback_encoding='utf-8')
  File "/opt/project/venv/lib/python3.6/site-packages/pygount/analysis.py", line 512, in source_analysis
    elif not has_lexer(source_path):
  File "/opt/project/venv/lib/python3.6/site-packages/pygount/analysis.py", line 465, in has_lexer
    result = bool(pygments.lexers.find_lexer_class_for_filename(source_path))
  File "/opt/project/venv/lib/python3.6/site-packages/pygments/lexers/__init__.py", line 168, in find_lexer_class_for_filename
    for cls in find_plugin_lexers():
  File "/opt/project/venv/lib/python3.6/site-packages/pygments/plugin.py", line 53, in find_plugin_lexers
    yield entrypoint.load()
  File "/opt/project/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/opt/project/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/opt/project/venv/lib/python3.6/site-packages/IPython/__init__.py", line 55, in <module>
    from .terminal.embed import embed
  File "/opt/project/venv/lib/python3.6/site-packages/IPython/terminal/embed.py", line 16, in <module>
    from IPython.terminal.interactiveshell import TerminalInteractiveShell
  File "/opt/project/venv/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 80, in <module>
    if not _stream or not hasattr(_stream, 'isatty') or not _stream.isatty():
ValueError: I/O operation on closed file

**Comment by decaz** [comment]
I see you are using IPython. Can you check coverage2clover without it?

**Comment by tumb1er** [comment]
@decaz if you don't mind, I'll leave it to you, ok?

**Comment by tumb1er** [comment]
Looks like something is trying to output something to stdout/stderr (or read from stdin) and parent process closed corresponding file descriptors.
